apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30437
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
        - name: init-grafana-config
          image: busybox
          volumeMounts:
            - name: grafana-config-volume
              mountPath: /etc/grafana
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_SERVER_ROOT_URL
              value: "http://89.252.184.15:30437/grafana/"
          volumeMounts:
            - name: grafana-config-volume
              mountPath: /etc/grafana
      volumes:
        - name: grafana-config-volume
          configMap:
            name: grafana-config

