apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    domain = 89.252.184.15
    http_port = 3000
    root_url = http://89.252.184.15:30437/grafana/
    serve_from_sub_path = true

    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [analytics]
    check_for_updates = true

    [log]
    mode = console
    level = info

    [security]
    admin_user = admin
    admin_password = admin # Güvenlik açısından bu şifreyi değiştirmeniz önerilir.

    [users]
    allow_sign_up = true
    allow_org_create = true

    [auth.anonymous]
    enabled = false

    [database]
    type = sqlite3
    path = grafana.db

    [session]
    provider = file

    root_url = http://89.252.184.15:30437/grafana/

